<?php
$title = ('Shows Directory');

$this->assets->collection('custom_css')->addCss('vendor/world-flags-sprite/stylesheets/flags16.css');

$cols = \DF\Utilities::columns($podcasts, 2);
?>

<div class="row">
<? foreach($cols as $col): ?>
    <div class="col-md-6">
        <?
        echo $this->viewHelper->renderCommon('podcast', array('podcasts' => $col));
        ?>
    </div>
<? endforeach; ?>
</div>